{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openoms.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openoms.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.api.host }}
      secretName: {{ .Values.ingress.api.tlsSecret }}
    - hosts:
        - {{ .Values.ingress.dashboard.host }}
      secretName: {{ .Values.ingress.dashboard.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openoms.fullname" . }}-api
                port:
                  name: http
    - host: {{ .Values.ingress.dashboard.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openoms.fullname" . }}-dashboard
                port:
                  name: http
{{- end }}
